// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-3XIANmW9mE3Zo-R2ZgtDBQNHJPP57A4',
    appId: '1:846907332518:web:e07e9dbdc4be97dc75e167',
    messagingSenderId: '846907332518',
    projectId: 'masenochat',
    authDomain: 'masenochat.firebaseapp.com',
    storageBucket: 'masenochat.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI1E1f88LEBmabGgsNp9vn4tUttgGVOFE',
    appId: '1:846907332518:android:9df4af9d4ab44ffc75e167',
    messagingSenderId: '846907332518',
    projectId: 'masenochat',
    storageBucket: 'masenochat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSrpa0k5dE3QB17PfuM6EHnKKmZyzYH5g',
    appId: '1:846907332518:ios:e1b965482798419275e167',
    messagingSenderId: '846907332518',
    projectId: 'masenochat',
    storageBucket: 'masenochat.appspot.com',
    iosBundleId: 'com.example.masenochat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSrpa0k5dE3QB17PfuM6EHnKKmZyzYH5g',
    appId: '1:846907332518:ios:c62ed3a11f3db2c075e167',
    messagingSenderId: '846907332518',
    projectId: 'masenochat',
    storageBucket: 'masenochat.appspot.com',
    iosBundleId: 'com.example.masenochat.RunnerTests',
  );
}
