// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDms7lhetEydD8ZK3thRSxQd-k4IlQ9SDs',
    appId: '1:282174447062:web:d98506c8c3060541c3d877',
    messagingSenderId: '282174447062',
    projectId: 'msn-chat-app-46b42',
    authDomain: 'msn-chat-app-46b42.firebaseapp.com',
    storageBucket: 'msn-chat-app-46b42.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC1kJIEX2-lSf_RGt8-z9LbAh_4bjjD_A',
    appId: '1:282174447062:android:b0c0f55f83667c70c3d877',
    messagingSenderId: '282174447062',
    projectId: 'msn-chat-app-46b42',
    storageBucket: 'msn-chat-app-46b42.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXB84XJ3QTG8mz1NaQDU9BZrX34Ebb5RA',
    appId: '1:282174447062:ios:853e11a9ea6e28e0c3d877',
    messagingSenderId: '282174447062',
    projectId: 'msn-chat-app-46b42',
    storageBucket: 'msn-chat-app-46b42.appspot.com',
    iosBundleId: 'com.example.msnChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXB84XJ3QTG8mz1NaQDU9BZrX34Ebb5RA',
    appId: '1:282174447062:ios:78e9f70c1ad5d400c3d877',
    messagingSenderId: '282174447062',
    projectId: 'msn-chat-app-46b42',
    storageBucket: 'msn-chat-app-46b42.appspot.com',
    iosBundleId: 'com.example.msnChat.RunnerTests',
  );
}
